# Generated by Django 5.2.3 on 2025-07-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wallettransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('BET', 'Bet Placed'), ('WIN', 'Win Credited'), ('CANCEL', 'Bet Canceled')], max_length=10),
        ),
    ]
