# Generated by Django 5.2.3 on 2025-07-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wallettransaction_meta_alter_wallettransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
