# Generated by Django 5.2.3 on 2025-07-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_wallettransaction_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
